// LICENSE>>
// Copyright 2025 M5 Dev (FM Infinite Authors)
// << LICENSE

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
