// LICENSE>>
// Copyright 2025 M5_Dev (FM Infinite Authors)
// << LICENSE

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "FM-Infinite"
include ':app'
